### ISSUE TITLE
Tests: Write them

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#57]
An ongoing process.

- [X] RSpec *(mostly)*
- [ ] Fix the TODOs in RSpec
- [ ] DRY up our controller specs (#586)
- [x] Feature specs (move from Cucumber to RSpec & Capybara?)
- [ ] Thorough helper specs
- [ ] View specs
- [ ] Thorough mailer specs (might be complete?)
- [x] Job specs? (Might require using ActiveJob for our jobs)
- [ ] Javascript (#389)

**Comment by Throne3d** [comment]
RSpec tests are mostly done, now. Cucumber up next?

**Comment by Throne3d** [comment]
We're investigating using RSpec (and Capybara) for request and feature specs, as opposed to Cucumber (which we currently have set up for the feature specs).

Request specs are like controller specs, except in RSpec 3.5+ (and Rails 5.0+), controller tests (functional) are discouraged in favor of request specs (integrational), since the full routing, session and response parts, as well as other bits, of the stack, are made sure to work with the relevant request. This apparently helps to reduce edge case issues, though we may find it harder to test some things, such as where we currently access a controller's `assigns`, since it looks like this is removed. (We may need to artificially select the new model, in cases where new models are made, or select the model-to-be-updated in cases where that applies – I'm not sure.)

Feature specs are designed to test the application from a web browser's perspective, totally driven externally, integrationally. Apparently you can also test JavaScript integration using Capybara (and I believe it's by default set up to use Chrome as the browser it tests on, with screenshot support for failures!?). It seems useful to look into this.

Other things we might want to look into:

- [ ] Proper helper specs (go through helpers thoroughly)
- [ ] DRY up our controller specs (well, request specs when we get around to that), especially the areas that are like "requires login", "requires ID", "requires valid ID"
- [ ] View specs (which are less integrational and make sure the views contain proper data for the relevant assigns!)
- [ ] Improved mailer specs (we have these to an extent, but I'm not sure it's as comprehensive as it could/should be – do we test each location they're created, all the relevant params, and then that the relevant jobs produce the actual emails accurately with the relevant views and so on? We may want to look into fixtures with some sample data too.)
- [ ] Job specs? (Might require using ActiveJob for our jobs)

**Comment by Marri** [comment]
I generally test both jobs and mailers, did I not?

**Comment by Throne3d** [comment]
You do but I hadn't investigated anything at the time and wasn't sure if stuff would change with ActiveJob – I'll strike it off the list.

**Comment by Throne3d** [comment]
Closing - remaining missing tests are mostly view tests, which we have some plans to improve with Ruby 3.2 Kernel#eval stuff, and should be a separate issue
